[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-lxkbcommon",
]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/opt/llvm/bin/ld64.lld"]

# [unstable]
# codegen-backend = true
# [profile.dev]
# codegen-backend = "cranelift"
# [profile.dev.package."*"]
# codegen-backend = "llvm"

[build]
rustflags = ["-Z", "share-generics=y"]
